version: '3.1'
services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: dc
      MONGO_INITDB_ROOT_PASSWORD: gigaMongo
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8530:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dc
      ME_CONFIG_MONGODB_ADMINPASSWORD: gigaMongo
      ME_CONFIG_MONGODB_URL: mongodb://dc:gigaMongo@mongo:27017/
  ai-backend:
    image: mikkak/dungeoncrawler-ai:latest
    restart: unless-stopped
    ports:
      - "0.0.0.0:420:420"
    depends_on:
      -  mongo
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017