version: '3.1'

services:

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dc
      MONGO_INITDB_ROOT_PASSWORD: gigaMongo
    command: ["--bind_ip", "0.0.0.0"]

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dc
      ME_CONFIG_MONGODB_ADMINPASSWORD: gigaMongo
      ME_CONFIG_MONGODB_URL: mongodb://dc:gigaMongo@mongo:27017/


  ai-backend:
    image: mikkak/dungeoncrawler-ai
    restart: unless-stopped
    ports:
      - "420:420"
    depends_on:
     -  mongo
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017

